name: Deploy Next.js to S3 and CloudFront

on:
  workflow_run:
    workflows: ["Build and Test Next.js Frontend"]
    types:
      - completed
    branches:
      - main
  workflow_dispatch:
    inputs:
      run_id:
        description: 'run_id of uploaded artifact'
        required: false
        type: string

jobs:
  deploy-to-s3:
    name: Deploy to S3 and Invalidate CloudFront
    runs-on: ubuntu-latest
    if: ${{ (github.event_name == 'workflow_dispatch') || (github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.head_branch == 'main') }}
    environment: production

    steps:
      - name: Get artifact ID
        id: get_artifact
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const runId = github.event.inputs.run_id || github.event.workflow_run.id;
            const artifacts = await github.rest.actions.listWorkflowRunArtifacts({
              owner: context.repo.owner,
              repo: context.repo.repo,
              run_id: runId,
            });
            const artifact = artifacts.data.artifacts.find(a => a.name === "frontend-build");
            if (!artifact) {
              core.setFailed("Artifact 'frontend-build' not found.");
            } else {
              core.setOutput("artifact-id", artifact.id);
            }

      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: frontend-build
          path: frontend/out
          run-id: ${{ steps.get_artifact.outputs.artifact-id }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1

      - name: Deploy to S3
        run: aws s3 sync out s3://saburo-frontend --delete

      - name: Invalidate CloudFront cache
        run: aws cloudfront create-invalidation --distribution-id ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }} --paths "/*"