name: Build and Test Next.js Frontend

on:
  push:
    branches:
      - main
      - develop
    paths:
      - 'frontend/**'
      - '.github/workflows/ci.yml'
  pull_request:
    branches:
      - main
      - develop
    paths:
      - 'frontend/**'
  workflow_dispatch:

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: 'package-lock.json'

      - name: Install dependencies
        run: npm ci

      - name: Run linting
        run: npm run lint || echo "Linting not configured"

      - name: Run type check
        run: npm run typecheck || npm run check-types || echo "Type check not configured"

      - name: Run tests
        run: npm test || echo "No tests configured"

      - name: Build Next.js
        run: |
          NEXT_PUBLIC_API_URL="https://api.saburo.xyz" \
          NEXT_PUBLIC_ADMIN_PIN="${{ secrets.ADMIN_PIN }}" \
          NODE_ENV="production" \
          npm run build && npm run export

      - name: Upload build artifact
        if: github.event_name != 'pull_request'
        uses: actions/upload-artifact@v4
        with:
          name: frontend-build
          path: out
          retention-days: 7